
language: php

php:
  - '7.2'
  - nightly

before_script:
- composer self-update
- composer install --no-interaction

script:
- composer test

after_success:
- bash <(curl -s https://codecov.io/bash)
